name: Deploy Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            echo "🚀 Deploying update..."

            cd /var/www/top-reader

            git pull origin master

            echo "✅ Files updated"

            sudo systemctl reload nginx

            echo "🌐 Website refreshed"
